export const RULES={total:100,split:80,fill:20,manches:3} as const;
export type Player='A'|'B'; export type Phase='SPLIT_1_COMMIT'|'SPLIT_2_COMMIT'|'FILL_COMMIT'|'FINISHED';
export type Fill=readonly[number,number,number]; export type ErrorCode='WRONG_PHASE'|'ALREADY_COMMITTED'|'NOT_INTEGER'|'OUT_OF_RANGE'|'INVALID_FILL_TOTAL'|'NEGATIVE_FILL'|'MALFORMED_ACTION'|'INVALID_STATE';
export type Game={phase:Phase; split:Readonly<Record<Player,readonly number[]>>; fill:Readonly<Partial<Record<Player,Fill>>>; pending:Readonly<Partial<Record<Player,number|Fill>>>; result?:{scores:readonly[number,number];outcome:'A_WIN'|'DRAW'|'B_WIN'}};
export const createGame=():Game=>({phase:'SPLIT_1_COMMIT',split:{A:[],B:[]},fill:{},pending:{}});
const err=(code:ErrorCode):never=>{throw Object.assign(new Error(code),{code});}; const other=(p:Player):Player=>p==='A'?'B':'A';
const split3=(x:number[])=>RULES.split-x[0]-x[1]; const legalFill=(a:unknown):a is Fill=>Array.isArray(a)&&a.length===3&&a.every(x=>Number.isInteger(x)&&x>=0)&&a.reduce((s,x)=>s+x,0)===RULES.fill;
export function validateAction(g:Game,p:Player,a:number|Fill):void {if(g.pending[p]!==undefined)err('ALREADY_COMMITTED'); if(g.phase==='SPLIT_1_COMMIT'){if(!Number.isInteger(a))err('NOT_INTEGER');if(typeof a!=='number'||a<1||a>RULES.split-2)err('OUT_OF_RANGE');return;}if(g.phase==='SPLIT_2_COMMIT'){if(!Number.isInteger(a))err('NOT_INTEGER');const m1=g.split[p][0];if(typeof a!=='number'||a<1||a>RULES.split-m1-1)err('OUT_OF_RANGE');return;}if(g.phase==='FILL_COMMIT'){if(!Array.isArray(a))err('MALFORMED_ACTION');if((a as number[]).some(x=>x<0))err('NEGATIVE_FILL');if(!legalFill(a))err('INVALID_FILL_TOTAL');return;}err('WRONG_PHASE');}
export function commitAction(g:Game,p:Player,a:number|Fill):Game {validateAction(g,p,a);const pending={...g.pending,[p]:a};if(pending[other(p)]===undefined)return {...g,pending};if(g.phase==='SPLIT_1_COMMIT')return {...g,split:{A:[pending.A as number],B:[pending.B as number]},pending:{},phase:'SPLIT_2_COMMIT'};if(g.phase==='SPLIT_2_COMMIT'){const split={A:[...g.split.A,pending.A as number],B:[...g.split.B,pending.B as number]};return {...g,split:{A:[...split.A,split3(split.A)],B:[...split.B,split3(split.B)]},pending:{},phase:'FILL_COMMIT'};}const fill={A:pending.A as Fill,B:pending.B as Fill};return {...g,fill,pending:{},phase:'FINISHED',result:resolveResult({...g,fill} as Game)};}
export function enumerateFillActions():Fill[]{const a:Fill[]=[];for(let x=0;x<=RULES.fill;x++)for(let y=0;y<=RULES.fill-x;y++)a.push([x,y,RULES.fill-x-y]);return a;}
export function resolveResult(g:Game){if(g.split.A.length!==3||!g.fill.A||!g.fill.B)err('INVALID_STATE');const m=[0,1,2].map(i=>g.split.A[i]+g.fill.A[i]-g.split.B[i]-g.fill.B[i]);const aw=m.filter(x=>x>0).length, bw=m.filter(x=>x<0).length;return {scores:[aw+.5*(3-aw-bw),bw+.5*(3-aw-bw)] as const,outcome:aw>bw?'A_WIN':aw<bw?'B_WIN':'DRAW' as const};}
export const serializeGameState=(g:Game)=>JSON.stringify(g); export const deserializeGameState=(s:string)=>JSON.parse(s) as Game;
